language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - python setup.py install
  - pip install coveralls
  - pip install nose

script:
  - coverage run --source=porter -m pytest test.py

after_success:
  - coveralls
